// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0EFYWcLxwqyD_f0FbgZDvsjpeLOfDZJg',
    appId: '1:723919088120:web:fdc774ba10082732860e0d',
    messagingSenderId: '723919088120',
    projectId: 'jobpilot-a143f',
    authDomain: 'jobpilot-a143f.firebaseapp.com',
    storageBucket: 'jobpilot-a143f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDihsf3Otljg4IHGhECJHutu7kn7PC_x7I',
    appId: '1:723919088120:android:f7aa3b9e6e528b47860e0d',
    messagingSenderId: '723919088120',
    projectId: 'jobpilot-a143f',
    storageBucket: 'jobpilot-a143f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl9SjEj9PYx63De4-VaFsjRZQMSu-SNRw',
    appId: '1:723919088120:ios:24d59873748e2914860e0d',
    messagingSenderId: '723919088120',
    projectId: 'jobpilot-a143f',
    storageBucket: 'jobpilot-a143f.firebasestorage.app',
    iosBundleId: 'com.example.jobPilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl9SjEj9PYx63De4-VaFsjRZQMSu-SNRw',
    appId: '1:723919088120:ios:24d59873748e2914860e0d',
    messagingSenderId: '723919088120',
    projectId: 'jobpilot-a143f',
    storageBucket: 'jobpilot-a143f.firebasestorage.app',
    iosBundleId: 'com.example.jobPilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0EFYWcLxwqyD_f0FbgZDvsjpeLOfDZJg',
    appId: '1:723919088120:web:ab80b29a7bb46fcf860e0d',
    messagingSenderId: '723919088120',
    projectId: 'jobpilot-a143f',
    authDomain: 'jobpilot-a143f.firebaseapp.com',
    storageBucket: 'jobpilot-a143f.firebasestorage.app',
  );
}
